### PR TITLE
Support for iOS 10

### PR DESCRIPTION
**Pull request by gdmarquez90**
https://bugzilla.xamarin.com/show_bug.cgi?id=44156

### CODE REVIEW

**Comment by gdmarquez90** [comment]
@olegoid should i add link from ios8 project to ios10 new project ?

**Comment by olegoid** [comment]
@gdmarquez90 if sample now has support for iOS 10 and demonstrates new APIs introduced in iOS 10 please move it to ios10 folder and leave `MOVETO.md` file in `ios8/QuickContacts`.

Add a link to a new sample location in `MOVETO.md` file.

**Comment by conceptdev** [comment]
hey guys, can you also ping docs when samples (that are in the gallery) are moved? we need to create a redirect so that the moved sample doesn't result in 404 on the website

eg. this sample will go from
https://developer.xamarin.com/samples/monotouch/ios8/QuickContacts/
to
https://developer.xamarin.com/samples/monotouch/ios10/QuickContacts/

and we need to redirect to ensure any existing links to the old URL get redirected. tagging me, or create an issues in *documentation* repo, or whatever works.
thanks!

**Comment by olegoid** [comment]
Thanks for bringing this up @conceptdev

**Comment by gdmarquez90** [comment]
The new classes are available since ios9 so i moved the new project to the ios9 directory. Also, i leaved the old project with ios8 compatibility in the ios8 directory.

**Pull request merged**
