### PR TITLE
Fix crash in Chat sample and make it work correctly

### PR DESCRIPTION
**Pull request by MarLoe**
The Chat sample crash on iOS 11 and above. Also does not work correctly in regards to showing/hiding keyboard.

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]
+1 minnor style issue.

**Comment by rolfbjarne** [comment]
Closing since CLA requirement has not been met.

**Comment by MarLoe** [comment]
CLA signed

**Comment by MarLoe** [comment]
@microsoft-github-policy-service agree

**Review by rolfbjarne — APPROVED** [review]

**Pull request merged**
