### PR TITLE
51575: added permissions for microphone access on plist. 

### PR DESCRIPTION
**Pull request by bubudrc**

### CODE REVIEW

**Comment by olegoid** [comment]
Hi @bubudrc, thanks for the PR!

I believe changes in `Sound.csproj` and `SoundViewController.cs` files are not required for the fix.

**Comment by bubudrc** [comment]
@olegoid 
Yes, changed in `Sound.csproj` are not necessary, but in `SoundViewController.cs` I added the condition to know if the user granted the Microphone permission in this lines:

```
var session = AVAudioSession.SharedInstance();
session.RequestRecordPermission(delegate (bool granted)
{
Console.WriteLine("Audio Permission: " + granted);
...
```

if the user hasn't the permissions, I added a log msg

**Comment by olegoid** [comment]
Okay @bubudrc, could you do the following:
* Remove changes in `Sound.csproj`
* Change code formatting in `SoundViewController.cs`(position of curly braces and whitespaces).

**Comment by bubudrc** [comment]
@olegoid DONE

**Pull request merged**
