### PR TITLE
Update 'MapCallouts' sample

### PR DESCRIPTION
**Pull request by mykyta-bondarenko**
- updated assets
- re-created projects
- updated main and added launch storyboards
- updated screenshots and readme, license, metadata
- fixed iPhone X view
- all changes are related to the original sample

### CODE REVIEW

**Comment by conceptdev** [comment]
VSMac 8.0 Preview build 869 throws the error
Xamarin iOS  12.2.1.12
Xcode 10.1 10B61

also VSMac Preview build 1470

also VSMac 7.6.11 build 9 (stable)
Xamarin iOS 12.0.0.15

screen shot 2019-01-28 at 10 50 50 am

<details>
  <summary>Visual Studio about box</summary>
Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.7 Preview (7.7 build 1470)
Installation UUID: 438a502a-c8e1-49d7-943b-e958bc9a8724
Runtime:
	Mono 5.18.0.237 (2018-08/51c4f454022) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 518000237

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.6
	2.1.2
	2.1.1
	2.0.5
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.500/Sdks
SDK Versions:
	2.1.500
	2.1.302
	2.1.301
	2.1.4
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

Xamarin.iOS
Version: 12.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

Xamarin.Android
Version: 9.1.4.2 (Visual Studio Enterprise)
Android SDK: /Users/crdun/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Java SDK: /Users/crdun/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 7.7.1.0
Hash: a173bd27

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 707001470
Git revision: 7aff2dc1f28d711d11d63d79b2a4c49cda217189
Build date: 2018-09-28 17:39:40+00
Build branch: release-7.7-preview3
Xamarin extensions: ab5106e52c8cb870de8b90dfc0f298e00a37051d

Operating System
Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

</details>


<details>
  <summary>Application call stack</summary>
MapKit.MKAnnotationView..ctor(MapKit.IMKAnnotation annotation, string reuseIdentifier) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/MapKit/MKAnnotationView.g.cs:103
MapCallouts.CustomAnnotationView..ctor(MapKit.MKAnnotation annotation, string reuseIdentifier) in /Users/crdun/ProjectsXamarin/ios-samples/MapCallouts/MapCallouts/CustomAnnotationView.cs:24
ObjCRuntime.Messaging.IntPtr_objc_msgSend_IntPtr_IntPtr() in 
MapKit.MKMapView.DequeueReusableAnnotation(string identifier, MapCallouts.Annotations.CustomAnnotation annotation) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/MapKit/MKMapView.g.cs:405
MapCallouts.MapViewController.SetupCustomAnnotationView(MapCallouts.Annotations.CustomAnnotation annotation, MapKit.MKMapView mapView) in /Users/crdun/ProjectsXamarin/ios-samples/MapCallouts/MapCallouts/MapViewController.cs:237
MapCallouts.MapViewController.GetViewForAnnotation(MapKit.MKMapView mapView, MapCallouts.Annotations.CustomAnnotation annotation) in /Users/crdun/ProjectsXamarin/ios-samples/MapCallouts/MapCallouts/MapViewController.cs:168
ObjCRuntime.Messaging.void_objc_msgSend_MKCoordinateRegion_bool() in 
MapKit.MKMapView.SetRegion(MapKit.MKCoordinateRegion region, bool animated) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/MapKit/MKMapView.g.cs:839
MapCallouts.MapViewController.CenterMapOnSanFrancisco() in /Users/crdun/ProjectsXamarin/ios-samples/MapCallouts/MapCallouts/MapViewController.cs:82
MapCallouts.MapViewController.set_DisplayedAnnotations(System.Collections.Generic.List<MapKit.MKAnnotation> value) in /Users/crdun/ProjectsXamarin/ios-samples/MapCallouts/MapCallouts/MapViewController.cs:45
MapCallouts.MapViewController.ShowAllAnnotations(MapCallouts.MapViewController sender) in /Users/crdun/ProjectsXamarin/ios-samples/MapCallouts/MapCallouts/MapViewController.cs:112
MapCallouts.MapViewController.ViewDidLoad() in /Users/crdun/ProjectsXamarin/ios-samples/MapCallouts/MapCallouts/MapViewController.cs:64
UIKit.UIApplication.UIApplicationMain() in 
UIKit.UIApplication.Main(string[] args, System.IntPtr principal, System.IntPtr delegate) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:79
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:63
MapCallouts.Application.Main(string[] args) in /Users/crdun/ProjectsXamarin/ios-samples/MapCallouts/MapCallouts/Main.cs:12
</details>

screen shot 2019-01-28 at 11 08 29 am

**Comment by mykyta-bondarenko-gl** [comment]
Oh, yeah, you are right, there was an issue. It's fixed in the master now. 
[Here](https://github.com/xamarin/xamarin-macios/issues/5345) you can find details.

**Comment by conceptdev** [comment]
@mykyta-bondarenko-gl thanks - we can't publish until it will work for our customers, so when the fix from master hits stable, we can merge this.

**Comment by mykyta-bondarenko-gl** [comment]
It's under `master`, `d16-0` and `xcode10.2` branches

**Pull request closed without merging**
