### PR TITLE
Added method to call the correct delegate one

### PR DESCRIPTION
**Pull request by ivanherreragl**

### CODE REVIEW

**Comment by olegoid** [comment]
@ivanherreragl could you attach link to the bug in PR description

**Comment by ivanherreragl** [comment]
For some reason the delegate is not correctly being set in the TableView and the delegate methods are being called in GrowRowTableViewController.cs. The line which does it is fine:

```
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			// Initialize table
			TableView.DataSource = new GrowRowTableDataSource(this);
			TableView.Delegate = new GrowRowTableDelegate (this);
			TableView.EstimatedRowHeight = 40f;
			TableView.ReloadData ();
		}
```
The solution is more like a patch, redirecting the method call to the correct delegate object.

**Comment by olegoid** [comment]
@ivanherreragl juts for my interest, have you tried to apply fix proposed by Rolf here - https://bugzilla.xamarin.com/show_bug.cgi?id=37448#c1 ?

**Comment by ivanherreragl** [comment]
Yes. With no luck. I'm not sure what should we edit in the designer file to make it work.

**Comment by ivanherreragl** [comment]
Ok. Removed the incorrect lines from the TableViewController designer file which were causing the wrong binding. This is now a cleaner solution. Should be good to merge.

**Comment by olegoid** [comment]
LGTM 👍

**Pull request merged**
