### PR TITLE
watchOS sample - Watch Connectivity - Application Context

### PR DESCRIPTION
**Pull request by b099l3**
I have added a watchOS sample that uses the WatchConnectivty framework. This uses a WCSession manager to manage the WCSession and sends data through application context. It could be extended to use messages or file transfers.

Inspired by these tutorials:
https://www.natashatherobot.com/watchconnectivity-application-context/ 
http://kristina.io/watchos-2-tutorial-using-application-context-to-transfer-data-watch-connectivity-2/

### CODE REVIEW

**Comment by olegoid** [comment]
@b099l3 thanks for your PR!

@gdmarquez90 could you review and test this sample?

**Comment by b099l3** [comment]
No worries, any question/issues let me know.

**Comment by gdmarquez90** [comment]
@olegoid i'm on it. Thanks @b099l3.

**Comment by olegoid** [comment]
It seems like everything is fine. @b099l3 thanks again for your contribution!

**Pull request merged**
