### PR TITLE
51615 fixed

### PR DESCRIPTION
**Pull request by bubudrc**

### CODE REVIEW

**Comment by GouriKumari** [comment]
This is also fixed. I would like @olegoid  to review the code change before  merging.

**Comment by bubudrc** [comment]
Done

**Comment by olegoid** [comment]
@bubudrc probably something is missing in your last commit ;) In diff I can see only that empty line was deleted.

**Comment by bubudrc** [comment]
@olegoid I reviewed the changes and all the spaces are tabs.... I tried to revert and rebuild the project, but the result has the same

**Comment by olegoid** [comment]
@bubudrc could you turn on invisible characters in your IDE? I think it will clear things out.

Not sure how to do it in VS bit XS you can do it in Xamarin Studio -> Preferences -> Text Editor -> Markers and Rulers -> Show Invisible Characters = Always

**Comment by bradumbaugh** [comment]
It seems that the changes made here are in **RosyWriterViewController.cs**, which is not actually used by the application. The primary view controller for the app is **RosyWriterViewControllerUniversal.cs**. I'm going to close this PR. Thanks for the contribution, though!

**Pull request closed without merging**
