### PR TITLE
Sample photo app fix

### PR DESCRIPTION
**Pull request by ivanherreragl**

### CODE REVIEW

**Comment by ivanherreragl** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=58336

**Comment by GouriKumari** [comment]
@ivanherreragl:  Can you include a PR only with https://github.com/xamarin/ios-samples/pull/173/commits/ba64a72b9d292814604f7d1d3cf3ba2f955f5676.

**Comment by iherrera** [comment]
https://github.com/xamarin/ios-samples/pull/177

**Comment by conceptdev** [comment]
PR https://github.com/xamarin/ios-samples/pull/177#event-1216764782 was merged. Other changes in _this_ PR seem unnecessary (eg. VisionMLSample being created and removed).

Perhaps any remaining changes could be submitted in separate PRs (one per sample), e.g. if  AVMetadataRecordPlay updates are still required?

**Comment by GouriKumari** [comment]
Closing this PR since the issue related to sample is fixed.

**Pull request closed without merging**
