### PR TITLE
[XI] fix the "SamplePhotoApp" project

### PR DESCRIPTION
**Pull request by mykyta-bondarenko-gl**

### CODE REVIEW

**Comment by mykyta-bondarenko-gl** [comment]
@GouriKumari  I found that I've fixed only iOS10 app, so I've added fix for the iOS11 app.

**Comment by mykyta-bondarenko-gl** [comment]
@bradumbaugh I only fixed an API bug, not worked on complete sample :)

**Comment by bradumbaugh** [comment]
@mykyta-bondarenko-gl This looks like a good change; will file an issue regarding the other problem I'm seeing

**Comment by mykyta-bondarenko-gl** [comment]
@bradumbaugh ok, thanks a lot!

**Pull request merged**
