### PR TITLE
[ios11] MusicKit Sample

### PR DESCRIPTION
**Pull request by SotoiGhost**
* Port of MusicKit Swift [sample](https://developer.apple.com/musickit/)
* .Net Standard 2.0 Console App to generate the [MusicKit Developer Token](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/AppleMusicWebServicesReference/SetUpWebServices.html#//apple_ref/doc/uid/TP40017625-CH2-SW1)

### CODE REVIEW

**Comment by conceptdev** [comment]
the TokenGenerator works great, and I was able to get music playing, but the search doesn't seem to show any results? I'm testing on an iPhone 7 Plus - any tips?

**Comment by SotoiGhost** [comment]
@conceptdev AFAIK, the MusicKit doesn't work well with simulator, I don't have the information at hand right now, but I suggest to test it on a physical device.

**Comment by conceptdev** [comment]
Yep, as I said, testing on iPhone 7 Plus (physical device). 

Does the **Search** work for you? What is a known-working search term?

**Comment by SotoiGhost** [comment]
@conceptdev I have just tested again the sample right out of the box and it worked for me. I'm using an iPhone 7 with iOS 11.0.1.

I searched for **Olafur**

**Comment by conceptdev** [comment]
🤔 i get no results, however my phone is on 11.0, so let me update iOS and re-test before further investigation. thanks.

**Pull request merged**
